/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_ym2149player_free: (a: number, b: number) => void;
export const ym2149player_currentSubsong: (a: number) => number;
export const ym2149player_frame_count: (a: number) => number;
export const ym2149player_frame_position: (a: number) => number;
export const ym2149player_generateSamples: (a: number, b: number) => [number, number];
export const ym2149player_generateSamplesInto: (a: number, b: number, c: number, d: any) => void;
export const ym2149player_getChannelStates: (a: number) => any;
export const ym2149player_get_registers: (a: number) => [number, number];
export const ym2149player_is_channel_muted: (a: number, b: number) => number;
export const ym2149player_is_playing: (a: number) => number;
export const ym2149player_metadata: (a: number) => number;
export const ym2149player_new: (a: number, b: number) => [number, number, number];
export const ym2149player_pause: (a: number) => void;
export const ym2149player_play: (a: number) => void;
export const ym2149player_position_percentage: (a: number) => number;
export const ym2149player_restart: (a: number) => void;
export const ym2149player_seek_to_frame: (a: number, b: number) => void;
export const ym2149player_seek_to_percentage: (a: number, b: number) => void;
export const ym2149player_setSubsong: (a: number, b: number) => number;
export const ym2149player_set_channel_mute: (a: number, b: number, c: number) => void;
export const ym2149player_set_color_filter: (a: number, b: number) => void;
export const ym2149player_set_volume: (a: number, b: number) => void;
export const ym2149player_state: (a: number) => [number, number];
export const ym2149player_stop: (a: number) => void;
export const ym2149player_subsongCount: (a: number) => number;
export const ym2149player_volume: (a: number) => number;
export const init_panic_hook: () => void;
export const __wbg_ymmetadata_free: (a: number, b: number) => void;
export const ymmetadata_author: (a: number) => [number, number];
export const ymmetadata_comments: (a: number) => [number, number];
export const ymmetadata_duration_seconds: (a: number) => number;
export const ymmetadata_format: (a: number) => [number, number];
export const ymmetadata_frame_count: (a: number) => number;
export const ymmetadata_frame_rate: (a: number) => number;
export const ymmetadata_title: (a: number) => [number, number];
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
